spring:
  profiles:
    active:
  mail:
    host: ${SMTP_MAIL_HOST:smtp.mail.yahoo.com}
    port: 587
    username: ${SMTP_MAIL_USERNAME:targetangle_rockband@yahoo.com}
    password: ${SMTP_MAIL_PASSWORD:nyeduzjkfefjkkkw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    job-store-type: jdbc
    jdbc:
      schema:
        classpath: org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
  datasource:
    url: ${DB_URL:jdbc:mysql://amvera-samntn-run-target-angle-rock-band-db/target_angle?&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:drvFI29@885}
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5020714111-6kql02l287ea6k9h84eainiep0b7ieel.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 2844097722479256
            clientSecret: c35b9c054a18198788994c8c975e702c
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v12.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v12.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v12.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  url: ${API_BASE_URL:https://target-angle-rock-band-backend-samntn.amvera.io}
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - ${OAUTH2_REDIRECT_URI:https://target-angle-rock-band-frontend-samntn.amvera.io/registration/oauth2/redirect}
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
server:
  port: ${SERVER_PORT:8080}

